name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  # Build
  build:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2021.1.24f1
        targetPlatform:
          - StandaloneWindows64
    steps:
      # Checkout
      - uses: actions/checkout@v2.3.2
        with:
          lfs: false
      # Cache
      - uses: actions/cache@v2.1.1
        with:
          path: NetworkedFlightGame/Library
          key: NetworkedFlightGame/Library-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-
      # Build
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
      # Upload
      - uses: actions/upload-artifact@v2.1.4
        with:
          name: Build
          path: Builds